### ISSUE TITLE
No longer works on Mac OS 12.3 since python 2.7 was removed

### ISSUE THREAD

**Issue by skynet01** [gillibrand/alfred-change-case#13]
Any way to update the script to use python3? I keep getting an error 
"Code 127: /bin/bash: python: command not found"

Thank you!

**Comment by gillibrand** [comment]
@skynet01 OK, I updated this to work with python3 plus a few other fixes. Try downloading it again and let me know if it works for you.

**Comment by gillibrand** [comment]
Thanks for the kind words. I've ignored this a long time and had a few other requests to fix it. I was dreading looking at it, then ended up having fun with it.
