### ISSUE TITLE
Works with Alfred 5?

### ISSUE THREAD

**Issue by trehehaeuser** [gillibrand/alfred-change-case#16]
Hi, I use Alfred 5 and it did not work. What can I do? Best, Thomas

**Comment by heyneff** [comment]
Thanks for making your workflow, I use it all the time. Something must have changed with Alfred 5. No longer working after upgrading. Have tried in 5.0.1, 5.0.2, and 5.0.3. Thanks for looking!

1. Trigger Alfred
2. Type 'case' Note that 'case' causes the workflow not to be displayed as an option so delete to 'cas'
3. Hit Enter, am presented with search options

**Comment by gillibrand** [comment]
I'm afraid that changes in Python on macOS has made this hard to support over different Alfred versions. I haven't been using Alfred for a while now and haven't upgraded to Alfred 5 personally. I don't expect to have the time to fix this any time soon. I know there are a few other Alfred extensions that do something similar, so I suggest you check them out for now.
